CREATE TABLE IF NOT EXISTS "ip" (
    addr VARCHAR(45) PRIMARY KEY,
    first_seen TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    nb_bad_attempts INTEGER NOT NULL DEFAULT 0
);
