ALTER TABLE "drop" ADD COLUMN IF NOT EXISTS type_id INTEGER NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS "redirect" (
    id SERIAL PRIMARY KEY,
    drop_id INTEGER NOT NULL REFERENCES "drop" (id),
    create_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name VARCHAR(255) NOT NULL,
    link VARCHAR(2048) NOT NULL
);
